version: '3.8'

services:
  spectral-session:
    image: hacktifytechnologies/spectral-session:1.0
    container_name: spectral-session
    ports:
      - "5000:5000"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - redis
    restart: unless-stopped

  redis:
    image: redis:7-alpine
    container_name: spectral-session-redis
    restart: unless-stopped
